version: 0.2
phases:
  build:
    commands:
      - echo Entered the build phase...
      - mvn clean package install
  post_build:
    commands:
      - echo Build completed successfully
artifacts:
  files:
    - target/customer-service-0.0.1-SNAPSHOT.jar
  discard-paths: yes